PhenoApps/Field-Book

- app/src/main/java/com/fieldbook/tracker/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/MainActivity.java
- app/src/main/java/com/fieldbook/tracker/fields/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/layoutConfig/SelectorLayoutConfigurator.java
- app/src/main/java/com/fieldbook/tracker/traits/TraitEditorActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/selector_dropdown.xml
Relocated all the dropdown selector code into SelectorLayoutConfigurator
Allow for any number of dropdown fields to be displayed
> allow for multiple dropdown selector fields

- app/src/main/java/com/fieldbook/tracker/MainActivity.java
> Fixed back arrow button

- app/src/main/java/com/fieldbook/tracker/MainActivity.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/DiseaseRatingTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/MultiCatTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/NumericTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/PercentTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/TextTraitLayout.java
Moved from onFocusChangeListener to managing clearing hints in the appropriate trait layouts as it wasn't working for all cases.
> Brapi synced trait delete NA handling

- app/src/main/java/com/fieldbook/tracker/ConfigActivity.java
- app/src/main/java/com/fieldbook/tracker/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/FileExploreActivity.java
- app/src/main/java/com/fieldbook/tracker/MainActivity.java
- app/src/main/java/com/fieldbook/tracker/MainActivity.java.bak
- app/src/main/java/com/fieldbook/tracker/fields/FieldAdapter.java
- app/src/main/java/com/fieldbook/tracker/fields/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/fields/FieldFile.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/AngleTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/AudioTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/BarcodeTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/BooleanTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/CategoricalTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/CounterTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/DateTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/DiseaseRatingTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/LabelPrintTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/LocationTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/MultiCatTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/NumericTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/PercentTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/PhotoTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/TextTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traitLayouts/TraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/NewTraitDialog.java
- app/src/main/java/com/fieldbook/tracker/traits/TraitAdapter.java
- app/src/main/java/com/fieldbook/tracker/traits/TraitEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/traits/TraitObject.java
I divided FieldFile into FieldFileCSV and FieldFileExcel in order to absorb the difference between CSV and Excel.
I separated NewTraitDialog from TraitEditorActivity.
I packed trait layouts, the part of trait changing elements, and the part of range changing elements.
In the process, I found some bugs and fixed them:
1. In FieldEditorActivity etc. we make it to the background and leave it a few minutes (2 minutes in my environment), and make it to the foreground. Then Field Book crashes.
2. When editing a trait in FieldEditorActivity not in English, the previous format is kept.
3. In FieldEditorActivity, relationship among initial, minimum, and maximum values is not checked.
4. MultiCategory trait does not work.
5. In Category and MultiCategory, category duplication is not checked.
6. In …
> Inamori branch

- app/src/main/java/com/fieldbook/tracker/activities/BrapiActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/BrapiExportActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/BrapiProgramActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/BrapiTraitActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/BrapiTrialActivity.java
- app/src/main/java/com/fieldbook/tracker/brapi/ApiError.java
- app/src/main/java/com/fieldbook/tracker/brapi/BrAPIService.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/BrapiServiceTest.java
> Integrated breeding platform brapi activity error codes

- app/src/main/java/com/fieldbook/tracker/brapi/BrAPIService.java
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #150 
* Hardware: Samsung Galaxy S7 Active
* SDK: Oreo (8) API 26
> small fix for issue #150

- app/src/main/java/com/fieldbook/tracker/traits/CategoricalTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/MultiCatTraitLayout.java
Simple bug fix for issues 190 and 196.
> fix for issue 190 and 196, updated layout params

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/traits/LabelPrintTraitLayout.java
Added a CollectActivity function that inserts label print observations (mainly records a timestamp). Updated label print trait layout to call the function when a successful print occurs.
> Issue 194 record label prints

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- build.gradle
Database was running into an illegal state exception during migration. This was causing the traits to not populate correctly (categories). I rolled back the migrator code to my pre-merge implementation.
Fixes # 211, 212
- [x ] Bug fix (non-breaking change which fixes an issue)
Tested on-device, fresh install. Loaded sample data, tested collect activity. Deleted all studies and re-imported manually as well.
> Bugfix 211 212

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/fieldbook/tracker/activities/BrapiExportActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/BrapiTraitActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIService.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
- app/src/main/java/com/fieldbook/tracker/dialogs/NewTraitDialog.java
- app/src/main/java/com/fieldbook/tracker/objects/TraitObject.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Work on integration of brapi v2 endpoints during hackathon, tested against breedbase.
Fixes #223 
Fixes #224 
Fixes #222 
* Hardware:
* SDK:
> Brapi v2 hackathon

- app/build.gradle
- app/src/main/java/com/fieldbook/tracker/database/SqlUtil.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes trait creation
> hotfix for queries that used sql functions or nested queries

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/SearchActivity.java
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableValueDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- app/src/main/java/com/fieldbook/tracker/dialogs/FieldCreatorDialog.kt
- app/src/main/java/com/fieldbook/tracker/location/gnss/NmeaParser.kt
- app/src/main/res/layout/listitem_search_results.xml
> Search hotfix

- app/src/main/java/com/fieldbook/tracker/activities/BrapiActivity.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
> Brapi database hotfix

- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
Fix for issue #303 
Also added some documentation to the function that was causing issues.
> Fix issue#303 

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
- app/src/main/java/com/fieldbook/tracker/traits/PhotoTraitLayout.java
> Fix for photo observations reappearing 

- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
Some BrAPI endpoints don't use coordinateX or coordinateY in their data. FB now defaults these values to -1.
> Updated default primary/secondary plot values to NA.

- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
Rep is always 1 currently.
Fixes # 315
> Added rep column to database export.

- app/src/main/java/com/fieldbook/tracker/database/SqlUtil.kt
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
* Hardware:
* SDK:
> Bugfix period in column names

- app/src/main/java/com/fieldbook/tracker/activities/TraitEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/dragsort/DragSortController.java
- app/src/main/res/values/strings.xml
Disabled options item menu if the user is dragging, also show a message.
Fixes #147
> Fixed trait layout when dragging and using options item menu

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/DataGridActivity.kt
- app/src/main/java/com/fieldbook/tracker/adapters/DataGridAdapter.java
- app/src/main/res/drawable/table_cell_highlighted.xml
- app/src/main/res/raw/changelog.xml
Clicking the data grid will now scroll to the current range id and trait id.
It will also highlight that cell with green.
Fixes # 275
> Data Grid scroll to current plot id and trait

- app/src/main/java/com/fieldbook/tracker/activities/TraitEditorActivity.java
Improved trait editor visibility toggling.
Fixes #305
> Trait visibility toggling

- app/src/main/java/com/fieldbook/tracker/activities/BrapiAuthActivity.java
- app/src/main/res/values/strings.xml
1. brapi auth would recursively ask to authorize in some cases (v2)
2. urls with http would cause app to crash (v2)
3. progress bar would hang when using invalid url (v1)
Fixes #285
> BrAPI auth bug fixes

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/preferences/DatabasePreferencesFragment.java
- app/src/main/java/com/fieldbook/tracker/utilities/ZipUtil.kt
- app/src/main/res/raw/changelog.xml
Changed Settings/Database/export to zip the db and shared preferences xml into a zip file.
Changed Settings/Database/import to unzip a db/pref file or import just a db file depending on the extension.
Fixes #167
> issue #167

- app/src/main/java/com/fieldbook/tracker/adapters/InfoBarAdapter.java
Added observation variables (traits) to info bar choices.
Fixes #273
> issue #273

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/TraitEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
- app/src/main/res/raw/changelog.xml
Collect activity now navigates to last trait that user was on.
Bugfix, real position was not set correctly when importing traits.
Fixes #368
> issue #368

- app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/async/ImportRunnableTask.java
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- app/src/main/java/com/fieldbook/tracker/objects/FieldFileObject.java
- app/src/main/java/com/fieldbook/tracker/utilities/Utils.java
- app/src/main/res/raw/changelog.xml
- app/src/main/res/values/strings.xml
Added various messages throughput file import process if something goes wrong.
Fixes #106
> Issue 106 - Added messages for field import

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
bugfix where timestamp wasn't queried when creating brapi observation object
bugfix within isBrapiSynced that didn't return correct boolean
bugfix in validate data Collect Activity
Fixes #290
> fixes issue #290

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeoNavPreferencesFragment.kt
- app/src/main/res/xml/preferences_geonav.xml
> Fixed geonav preference ui not updating.

- app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
> brapi preference bugfix for advanced auth settings visibility

- app/src/main/java/com/fieldbook/tracker/dialogs/DatePickerFragment.kt
- app/src/main/java/com/fieldbook/tracker/traits/DateTraitLayout.java
Fixed bug where saved date was improperly shown.
> Fixed date trait not using last saved date correctly.

- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
- app/src/main/res/raw/changelog.xml
Fix for issue #402 but implemented for SAF storage on issue #120
> Fix for issue 402

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
Fix for issue #405 
Added exp id to database and table queries.
> db fix for deleting studies

- app/src/main/java/com/fieldbook/tracker/activities/DataGridActivity.kt
fixed datagrid when datahelper instance is closed
fixes #426 and #428
> issue #426/#428

- app/src/main/java/com/fieldbook/tracker/preferences/GeoNavPreferencesFragment.kt
added permission check for bluetooth connect on sdk 31+
fixes #427
> issue #427

- app/src/main/res/xml/preferences_brapi.xml
fixes #425 
xml had an array reference when it should have been a string
> changed label/val brapi pref default value from array to string

- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
DataHelper open call
Fixes #433
> issue #433

- app/src/main/java/com/fieldbook/tracker/activities/SearchActivity.java
DataHelper open call
Fixes #436
> issue #436

- app/src/main/java/com/fieldbook/tracker/database/models/ObservationModel.kt
- app/src/main/java/com/fieldbook/tracker/storage/StorageMigratorFragment.kt
Fixed migrator failing when observation has a null variable db id.
Fixes #437
> issue #437

- app/src/main/java/com/fieldbook/tracker/activities/BrapiAuthActivity.java
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
* Hardware:
* SDK:
> fixed the back stack issue for BrAPI Auth

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralPreferencesFragment.java
- app/src/main/res/raw/changelog.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_general.xml
> added options to general toolbar next entry preference

- app/build.gradle
- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/location/gnss/ConnectThread.kt
- app/src/main/java/com/fieldbook/tracker/location/gnss/ConnectedThread.kt
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralPreferencesFragment.java
- app/src/main/res/menu/menu_data_grid.xml
- app/src/main/res/raw/changelog.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_general.xml
increased communications byte array, added exception catching
added security checks in collect activity for disconnecting/connecting bluetooth devices
> v5.2 bugfixes

- app/build.gradle
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
- app/src/main/java/com/fieldbook/tracker/preferences/DatabasePreferencesFragment.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
quoted identifiers in sort query
issue #473
> fix for #473

- CODE_OF_CONDUCT.md
- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/traits/AngleTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/AudioTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/BaseTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/BooleanTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/CategoricalTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/CounterTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/DateTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/DiseaseRatingTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/GNSSTraitLayout.kt
- app/src/main/java/com/fieldbook/tracker/traits/LayoutCollections.java
- app/src/main/java/com/fieldbook/tracker/traits/LocationTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/MultiCatTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/NumericTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/PercentTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/PhotoTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/TextTraitLayout.java
- app/src/main/res/drawable/ic_lock_clock.xml
- app/src/main/res/raw/changelog.xml
- app/src/main/res/values/strings.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Added three states to lock.
Unlocked/Locked - normal
Frozen - no data can be edited
I can change this so default values can be edited, comment if that's what you prefer.
Also, traits with default values will be automatically saved to the database when navigated to. I can change this to be trait dependent.
> updated locking feature to locked/unlocked/frozen

- app/build.gradle
- app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/objects/FieldFileObject.java
- app/src/main/res/raw/changelog.xml
Fixes #480
Cloud files weren't parsing extensions correctly.
Tested on a google drive file.
> Cloud Import Fix #480

- app/src/main/java/com/fieldbook/tracker/location/GPSTracker.java
- app/src/main/java/com/fieldbook/tracker/utilities/GeodeticUtils.kt
- app/src/main/res/raw/changelog.xml
Location parameter changes.
Fixes #477
> v5.3/bug/gnss_changes/477

- app/src/main/java/com/fieldbook/tracker/activities/BrapiExportActivity.java
- app/src/main/java/com/fieldbook/tracker/brapi/model/FieldBookImage.java
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
Fixes brapi image export.
Fixes #483
> v5.3/bug/brapi_image_export/483

- app/build.gradle
- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- app/src/main/java/com/fieldbook/tracker/preferences/DatabasePreferencesFragment.java
Multiple bug fixes.
Added a check that clears selected field when an update occurs, let me know if you want this to only happen for this 5.3 update.
> Bug fixes for v5.3

- app/src/main/java/com/fieldbook/tracker/activities/BrapiAuthActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
> Brapi url preference fixes

- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
Fix for multiple fields with the same plot attributes.
> Db bug fix

- app/src/main/java/com/fieldbook/tracker/activities/TraitEditorActivity.java
- app/src/main/res/raw/changelog.xml
- app/src/main/res/values/strings.xml
Added check to not export traits when traits table is empty. Fixes #322
> Added option to delete traits when importing traits.

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
- app/src/main/java/com/fieldbook/tracker/adapters/FieldSortAdapter.kt
- app/src/main/java/com/fieldbook/tracker/adapters/SortAdapter.kt
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- app/src/main/java/com/fieldbook/tracker/dialogs/FieldSortController.kt
- app/src/main/java/com/fieldbook/tracker/dialogs/FieldSortDialog.kt
- app/src/main/java/com/fieldbook/tracker/dialogs/SortDialog.kt
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
- app/src/main/res/drawable/circle_background.xml
- app/src/main/res/drawable/sort_ascending.xml
- app/src/main/res/drawable/sort_descending.xml
- app/src/main/res/layout/dialog_field_sort.xml
- app/src/main/res/layout/list_item_field_sort.xml
- app/src/main/res/raw/changelog.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Basic recycler view / adapter that lets you drag and drop as well.
Fixes #350
> Updated sort order dialog for field editor

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/SummaryFragment.kt
- app/src/main/java/com/fieldbook/tracker/adapters/SummaryAdapter.kt
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
- app/src/main/java/com/fieldbook/tracker/traits/TextTraitLayout.java
- app/src/main/res/drawable/arrow_left.xml
- app/src/main/res/drawable/chevron_left.xml
- app/src/main/res/drawable/chevron_right.xml
- app/src/main/res/drawable/pencil.xml
- app/src/main/res/layout/fragment_summary.xml
- app/src/main/res/layout/list_item_summary.xml
- app/src/main/res/menu/menu_fragment_summary.xml
- app/src/main/res/values/strings.xml
Added ability to filter plot attributes / traits that are viewable in the summary.
Items can be clicked to navigate to that trait.
Next/Previous button to move entries.
I did't add swipe to move entries because this was clashing with the scroll view and it didn't seem right. Also it would be a hidden feature which we typically haven't done in the past, replaced with buttons.
Fixes #71 #317
> Summary update

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
> fix to persist data lock state

- app/src/main/java/com/fieldbook/tracker/adapters/InfoBarAdapter.java
> Bug Infobar Prefixes Missing

- app/src/main/java/com/fieldbook/tracker/views/RangeBoxView.kt
> Bug Fix Next Entry Sound

- app/src/main/java/com/fieldbook/tracker/traits/GNSSTraitLayout.kt
Ui bug was causing gnss trait to crash.
> fixes #606

- app/src/main/java/com/fieldbook/tracker/adapters/TraitAdapter.kt
bug fix for trait editor, checkbox state was not valid for long lists
> fixes #604

- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
- app/src/main/res/raw/changelog.xml
fix handling malformed traits (null observation_variable_name) when exporting brapi observations
> fixes #617

- .github/workflows/pr-prerelease.yml
fixes problem with pr build failing when branch name contains "/"
```release-note
```
> process branch name to exclude / character from pr build apk names

- app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiExportActivity.java
- app/src/main/java/com/fieldbook/tracker/brapi/ApiErrorCode.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIService.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
- app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
Cleaned up the error handling for BrAPI export functionality discovered with Breedbase
Helps solve #630 
Related to https://github.com/solgenomics/sgn/pull/4571 but not dependent on it
```release-note
Cleaned up the error handling for BrAPI export functionality
```
> cleaned up some BrAPI export issues with Breedbase

- .github/workflows/pr-prerelease.yml
Fixes pr action rename apk step failure
```release-note
```
> fix truncated bash command

- app/build.gradle
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java
Bug fix for brapi v1 categories not importing correctly.
fixes #640
- [x ] `BUGFIX` (non-breaking change which fixes an issue)
```release-note
BrAPI V1 categorical trait import fix
```
> fix for v1 brapi categories not importing correctly

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/TraitEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/utilities/TapTargetUtil.kt
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
fixes issue where tutorial would crash on sequence start. 
modifies TapTargetUtil util to resolve outerCircleColor according to theme, and for other colors use defaults.
closes #631
```release-note
fixed tutorial crash bug
```
> Fix for tutorial crashes

- app/src/main/java/com/fieldbook/tracker/activities/SearchActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
- app/src/main/res/raw/changelog.xml
Adds search activity column and like selections as shared preferences and uses them as defaults for future searches
closes #691
```release-note
Search option selections saved for subsequent searches
```
> Search option selections saved for subsequent searches

- .github/workflows/github-release.yml
Alters git release workflow to run once a day, and only release if there have been changes to files in the app dir since the last release.
closes #700
```release-note
```
> run release action once daily, only build if changes to app/ since last release

- docs/source/trait-zebra.rst
adds troubleshooting section to print trait docs.
closes #494
```release-note
```
> add troubleshooting section to print trait docs

- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- app/src/main/java/com/fieldbook/tracker/utilities/InfoBarHelper.kt
Fixes #735 
```release-note
Fixed bug where "geo_coordinates" did not show in the Summary, DataGrid, or InfoBars.
```
> bugfix for geo_coordinates not showing in infobars and crashing datagrid

- app/src/main/java/com/fieldbook/tracker/dialogs/NewTraitDialog.java
- app/src/main/java/com/fieldbook/tracker/traits/CategoricalTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/MultiCatTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/utilities/CategoryJsonUtil.kt
> bugfix loading old categorical observation values

- app/src/main/java/com/fieldbook/tracker/preferences/GeoNavPreferencesFragment.kt
Adds code to the geonav pref fragement to show/hide geonav settings when geonav is enabled/disabled
closes #733
```release-note
Geonav checkbox hides settings when disabled
```
> Geonav checkbox hides settings when disabled

- app/src/main/java/com/fieldbook/tracker/location/gnss/NmeaParser.kt
Improved NMEA type matching in NmeaParser class.
Newest emlid reach firmware was receiving nmea types that were not being matched previously, added a more robust matching that should catch the new and any further additions.
```release-note
Improved GNSS message handling.
```
> added more robust NMEA type matching

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/PreferencesActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
- app/src/main/java/com/fieldbook/tracker/utilities/VerifyPersonHelper.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_profile.xml
Modifies the require person setting to default to true
closes #739
```release-note
require person defaults to true
```
> Set require person default to true

- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
if brapi is authenticated, brapi enabled preference should be enabled
```release-note
```
> delete brapi token when brapi is disabled

- .readthedocs.yaml
- docs/requirements.txt
- docs/source/conf.py
Documentation build fix
```release-note
```
> Fix readthedocs builds

- app/src/main/java/com/fieldbook/tracker/activities/TraitEditorActivity.java
Updated cancel string
```release-note
Updated trait editor delete all traits dialog text
```
> Fixed trait editor delete all traits cancel string

- app/src/main/java/com/fieldbook/tracker/objects/FieldFileObject.java
Closes #770
XLSX cells were null, causing app to crash when importing.
```release-note
Bugfix for some XLSX files.
```
> Bugfix for XLSX having a null cell.

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/utilities/GeoNavHelper.kt
- app/src/main/java/com/fieldbook/tracker/utilities/KeyboardListenerHelper.kt
Closes #744
Adjusts snackbar height based on softkeyboard
```release-note
Improved display of GeoNav messages when keyboard is displayed on screen.
```
> Fixed GeoNav snackbar hiding behind soft keyboard when in text trait.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/ScannerActivity.kt
- app/src/main/java/com/fieldbook/tracker/preferences/BetaPreferencesFragment.kt
- app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
- app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
- app/src/main/java/com/fieldbook/tracker/utilities/BarcodeScannerUtils.kt
- app/src/main/res/layout/activity_scanner.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_beta.xml
- build.gradle
- version.properties
_Added MLKit library for barcode scanning as a beta option.
If these changes fix a bug or resolves a feature request, be sure to link to that issue. #719_
```release-note
```
> issue/719: MLKit Integration

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/DataGridActivity.kt
- app/src/main/java/com/fieldbook/tracker/activities/TraitEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/adapters/TraitAdapter.kt
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationVariableDao.kt
- app/src/main/java/com/fieldbook/tracker/traits/AudioTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/BaseTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/BooleanTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/CategoricalTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/CounterTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/DateTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/DiseaseRatingTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/GNSSTraitLayout.kt
- app/src/main/java/com/fieldbook/tracker/traits/GoProTraitLayout.kt
- app/src/main/java/com/fieldbook/tracker/traits/LocationTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/MultiCatTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/NumericTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/PercentTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/PhotoTraitLayout.kt
- app/src/main/java/com/fieldbook/tracker/traits/TextTraitLayout.kt
- app/src/main/java/com/fieldbook/tracker/traits/UsbCameraTraitLayout.kt
- app/src/main/java/com/fieldbook/tracker/utilities/OldPhotosMigrator.kt
- app/src/main/java/com/fieldbook/tracker/views/RepeatedValuesView.kt
- app/src/main/java/com/fieldbook/tracker/views/TraitBoxView.kt
finding traits via their name was causing various issues, refactored codebase to use trait db id's instead
```release-note
```
> updated queries to use trait db id instead of names

- app/src/main/java/com/fieldbook/tracker/utilities/GeoNavHelper.kt
- app/src/main/java/com/fieldbook/tracker/utilities/GeodeticUtils.kt
Added title-encoded parameters as log header/columns. Updated log writing to not create new files, it not just appends to either "limited_log.csv" or "log.csv" depending on settings.
closes #758 
```release-note
GeoNav logs to one file now.
```
> Single geonav log file for short and long logs

- app/src/main/java/com/fieldbook/tracker/traits/GNSSTraitLayout.kt
closes #795
bug from persisting connection across navigation, UI was flickering when navigating across many plots
```release-note
GNSS Trait flickering fix
```
> fix gnss flickering

- .github/workflows/github-release.yml
Removes the build/action run number from version tag
closes #787
```release-note
```
> remove build number from versioning

- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/TraitEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/DatabasePreferencesFragment.java
- app/src/main/java/com/fieldbook/tracker/utilities/FileUtil.java
- app/src/main/res/values/strings.xml
Add share file on db export, similar to export option on main screen. Fixes #505 
```Share file while exporting database```
> Add share file on database export

- app/src/main/java/com/fieldbook/tracker/views/RangeBoxView.kt
- app/src/main/java/com/fieldbook/tracker/views/TraitBoxView.kt
- app/src/main/res/layout/view_range_box.xml
- app/src/main/res/layout/view_trait_box.xml
Add progress bar for plots and traits when the user navigates through the range and traits. Fixes #545
```Progress bar while navigating through plots```
> Add progress bar for plots and traits

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- app/src/main/java/com/fieldbook/tracker/dialogs/CollectAttributeChooserDialog.kt
- app/src/main/java/com/fieldbook/tracker/traits/LabelPrintTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/utilities/InfoBarHelper.kt
- app/src/main/res/values/strings.xml
Adds field name to infobar attribute options. Updates label print trait to use same attributes, and removes hardcoded strings.
closes #762
closes #785 
```release-note
Field name included in infobar attribute options
```
> Field name included in infobar attribute options

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
fix: select all should toggle all states
fix: swapped cancel and delete buttons
```release-note
Updated repeated measures dialog.
```
> repeated measures dialog fixes:

- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
This will require update/reinstall since COARSE_LOCATION was not in manifest.
```release-note
Bugfix: Collect screen now allows approximate location permissions
```
> Coarse Location Permission + Collect Activity Fix

- app/build.gradle
```release-note
Updated BrAPI client to v2.1
```
> feat: updated brapi client to v2.1

- app/src/main/res/layout/dialog_brapi_import.xml
fix: brapi import dialog has a scroll view now, before long descriptions would make it impossible to cancel/save
```release-note
Improved Brapi Field import dialog for fields with long descriptions.
```
> Brapi Field Import Dialog fix

- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
Case statement to match trait data types list and make case insensitive. 
```release-note
Fixed a bug when importing Traits via BrAPI, the wrong data type was being imported
```
> data types case insensitive

- app/src/main/res/layout/view_trait_box.xml
Fixes trait arrow sizes
```release-note
Fixes trait arrow sizes
```
> trait arrow fix

- app/src/main/java/com/fieldbook/tracker/utilities/FieldAudioHelper.kt
- version.properties
Fix shared pref reference
```release-note
Fixed shared prefs
```
> fix shared prefs

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/res/values/strings.xml
added tutorials for new features
```release-note
```
> fixes bug where tutorial crashed app

- app/src/main/java/com/fieldbook/tracker/database/SearchQueryBuilder.java
Fixed bug with search
```release-note
Fixed search
```
> Fixed bug with search

- app/src/main/java/com/fieldbook/tracker/utilities/GeoNavHelper.kt
bugfix for keeping timestamp formats consistent between android location api and nmea messages
```release-note
```
> bugfix for fix not showing correctly on external gps units

- app/src/main/java/com/fieldbook/tracker/preferences/GeoNavPreferencesFragment.kt
- app/src/main/java/com/fieldbook/tracker/utilities/FieldAudioHelper.kt
- app/src/main/java/com/fieldbook/tracker/utilities/GeoNavHelper.kt
- app/src/main/java/com/fieldbook/tracker/utilities/GeodeticUtils.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
Added simultaneous full and limited logging. Both these files will be added to the zip file along with field audio
```Added a new option to enable simultaneous logging for limited and full mode.```
> Add both logging mode

- app/src/main/java/com/fieldbook/tracker/activities/ScannerActivity.kt
- app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
- app/src/main/res/values/strings.xml
Refactors barcode scan options in brapi prefs to reduce code duplication and ensure that server scan and auto configure can handle both individual urls and json pref objects.
closes #851
```release-note
Improved barcode scanning in BrAPI preferences 
```
> Unify brapi scan handling code

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/traits/LabelPrintTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/traits/LayoutCollections.java
- app/src/main/java/com/fieldbook/tracker/utilities/PrintThread.kt
- app/src/main/res/layout/trait_label_print.xml
- Fixes bug in printer message receiver management that left multiple receivers registered to save multiple observations linked to non-active plots
- Modifies print observations to save number of label copies as value, rather than label size
- Refines trait layout spinners to put the most-changed value first (copies), keep the order consistent regardless of size, and reduce number of spinners must be scrolled to on smaller screens
Closes #943
_Please add a one-line changelog entry below. This will be copied to the changelog file during the release …
> Print observation fix

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
Bugfix, database export was not saving new preferences file correctly.
Fix for BOOX tablets, force disabled WAL mode which was causing database issues.
```release-note
```
> Preference and Boox Tablet fixes

- app/src/main/java/com/fieldbook/tracker/views/RangeBoxView.kt
Fixes issue where range progress bar would show incorrect progress after changing field sort order.
```release-note
updated range progress bar to work with changed sort orders
```
> modify updateCurrentRange to use index of obsunit within sorted list

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
- app/src/main/java/com/fieldbook/tracker/dialogs/SearchDialog.java
> fixes #965

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> hotfix for database upgrading issue

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/VisibleObservationVariableDao.kt
- app/src/main/java/com/fieldbook/tracker/views/RangeBoxView.kt
- app/src/main/res/values/strings.xml
Fixes bug where skip entries for all traits preference would crash collect activity by attempting to set traitboxview to a trait that wasn't visible.
closes #987
```release-note
Skip entries update and bugfix
```
> Skip entries update and bugfix

- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
Addresses problem where obs from deleted fields would still show up in some places if field layout was re-imported (same obs unit names)
closes #1004
```release-note
Fixed incomplete field data deletion
```
> Fix for incomplete field data deletion

- app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java
fix #976
fix for client id updating oidc url
```release-note
```
> v5 client id preference bugfix

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/dialogs/GeoNavCollectDialog.kt
- app/src/main/java/com/fieldbook/tracker/traits/GNSSTraitLayout.kt
- app/src/main/java/com/fieldbook/tracker/utilities/GeoNavHelper.kt
fix #855 
```release-note
Improved GeoNav and GNSS compatibility 
```
> V5 geonav gnss compatibility

- app/src/main/java/com/fieldbook/tracker/storage/StorageDefinerFragment.kt
- app/src/main/res/layout/fragment_storage_definer.xml
- app/src/main/res/values/strings.xml
closes #894
```release-note
imporved storage definer language
```
> improve storage definer language

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiAuthActivity.java
> replace redirect links

- app/src/main/java/com/fieldbook/tracker/traits/LabelPrintTraitLayout.java
- app/src/main/java/com/fieldbook/tracker/utilities/BluetoothUtil.kt
Ensure bluetooth permissions check and skip blank device names
closes #1034
```release-note
blank names excluded from bluetooth device chooser
```
> Skip blank names in bluetooth device chooser

- app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivityOld.java
- app/src/main/java/com/fieldbook/tracker/objects/FieldFileObject.java
cloud import fixes
cloud files couldn't be imported when clicking the arrow next to the cloud provider in the google file chooser
fix for cloud names showing as UUID
Closes #1046 
```release-note
Fix cloud import
```
> Cloud Import Fixes

- app/src/main/java/com/fieldbook/tracker/objects/FieldFileObject.java
Fixes bug where XLSX import skips empty cells, causing column shifts in imported data
closes #1038
```release-note
Update xlsx import to include all cells even when empty
```
> Update xlsx import to include all cells even when empty

- app/src/main/java/com/fieldbook/tracker/async/ImportCSVTask.java
Fix for traits being deleted when importing a new trait file
> fix_trait_import

- app/src/main/AndroidManifest.xml
> remove_image_video_permissions

- app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
- app/src/main/java/com/fieldbook/tracker/async/ImportRunnableTask.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- app/src/main/java/com/fieldbook/tracker/dialogs/FieldCreatorDialogFragment.kt
- app/src/main/res/layout/list_item_field_recycler.xml
```release-note
Fields with different BrAPI study IDs can now have the same name
```
___
> brapi_shared_study_names

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/interfaces/CollectController.kt
- app/src/main/java/com/fieldbook/tracker/traits/AbstractCameraTrait.kt
- app/src/main/java/com/fieldbook/tracker/utilities/ExifUtil.kt
- app/src/main/java/com/fieldbook/tracker/utilities/SensorHelper.kt
I didn't want to make too may changes to existing features that use sensor data yet. But eventually the new SensorHelper class can be the source of all sensor events.
Additions to exif include yaw/pitch/roll which are relative to the device. Yaw is not azimuth and does not point to magnetic north. This uses the "game" sensor which does not use the magnetometer and is thus more accurate.
```release-note
Image EXIF tag metadata includes the device pitch, roll, and yaw at the time of capture
```
___
> adding_sensor_data_to_exif

- app/src/main/java/com/fieldbook/tracker/activities/FieldDetailFragment.kt
- app/src/main/java/com/fieldbook/tracker/activities/brapi/io/BrapiStudyImportActivity.kt
- app/src/main/java/com/fieldbook/tracker/adapters/StudyAdapter.kt
- app/src/main/java/com/fieldbook/tracker/brapi/model/BrapiStudyDetails.java
- app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
- app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
- app/src/main/java/com/fieldbook/tracker/objects/FieldObject.java
- app/src/main/res/drawable/file.xml
- app/src/main/res/drawable/ic_trial.xml
- app/src/main/res/layout/fragment_field_detail.xml
- app/src/main/res/layout/list_item_study.xml
```release-note
Trial name included in BrAPI import and field details page
```
___
> add_trial_chip_to_study_list_items

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/views/RangeBoxView.kt
- app/src/main/java/com/fieldbook/tracker/views/TraitBoxView.kt
- app/src/main/res/values/strings.xml
```release-note
Swap navigation now changes position of entry/trait navigation instead of only behavior
```
___
> flip_flop_ui_arrows

- .github/workflows/process-pr-merge.yml
Fixes bug in process_pr_merge action where action was unable to pass the pr_body between steps
```release-note
```
___
> fix action pr body handling

- app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java
- app/src/main/java/com/fieldbook/tracker/views/SearchBar.kt
- app/src/main/res/layout/activity_fields.xml
- app/src/main/res/layout/list_item_field_recycler.xml
- app/src/main/res/layout/view_search_bar.xml
```release-note
Search box added to field list
```
___
> field_search

- .github/workflows/process-pr-merge.yml
Brings in parts of fix that were tested in sandbox but accidentally left out of last PR
```release-note
```
___
> process pr merge fix

- app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/FileExploreActivity.kt
- app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiExportActivity.java
- app/src/main/java/com/fieldbook/tracker/activities/brapi/io/BrapiStudyImportActivity.kt
- app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java
- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
- app/src/main/java/com/fieldbook/tracker/utilities/ExportUtil.kt
- app/src/main/java/com/fieldbook/tracker/views/RangeBoxView.kt
```release-note
Numerous bug fixes and enhancements 
```
___
> bugs_v6.0.5

- app/src/main/java/com/fieldbook/tracker/preferences/StoragePreferencesFragment.java
Closes #1161 
```release-note
Preferences are now correctly imported from database zip files
```
___
> Clear preferences only for .db files

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/res/values/strings.xml
> merge conflicts

- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
Closes #1177 
```release-note
Exporting with 'Only unique identifier' no longer shifts data
```
___
> export_short_bug_fix

- app/src/main/java/com/fieldbook/tracker/activities/brapi/io/BrapiStudyImportActivity.kt
Modifies brapi field import to save locationName and any attributes stored in additionalInfo
closes #560
```release-note
Additional attributes are now included when importing fields using BrAPI
```
___
> store location and any additionalInfo fields as attributes

- app/src/main/java/com/fieldbook/tracker/activities/brapi/io/filter/BrapiListFilterActivity.kt
- app/src/main/java/com/fieldbook/tracker/activities/brapi/io/filter/ListFilterActivity.kt
- app/src/main/res/layout/activity_brapi_trait_preprocess.xml
- app/src/main/res/layout/activity_list_filter.xml
- app/src/main/res/layout/activity_study_importer.xml
- app/src/main/res/layout/list_item_brapi_trait_format_selector.xml
- app/src/main/res/layout/list_item_label_checkbox.xml
- app/src/main/res/layout/list_item_study.xml
- app/src/main/res/layout/view_search_bar.xml
Closes #1195
```release-note
BrAPI Import background color is now white
```
___
> fix_new_brapi_import_theme

- app/src/main/java/com/fieldbook/tracker/utilities/SensorHelper.kt
Closes #1196 
```release-note
Angle trait animation has been reversed
```
___
> Reverse angle trait direction

- app/src/main/res/layout/activity_fields.xml
Fixes #1096
```release-note
Nearest field snackbar no longer overlaps add field button
```
___
> Fix snackbar overlapping

- app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java
- app/src/main/java/com/fieldbook/tracker/preferences/PreferenceKeys.kt
- app/src/main/java/com/fieldbook/tracker/preferences/ProfilePreferencesFragment.java
- app/src/main/java/com/fieldbook/tracker/utilities/PersonNameManager.kt
- app/src/main/java/com/fieldbook/tracker/utilities/VerifyPersonHelper.kt
- app/src/main/res/values/strings.xml
Closes #1045 
```release-note
User names are now saved in a list for rapid switching
```
___
> Show previous person names

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/fieldbook/tracker/activities/DataGridActivity.kt
- app/src/main/java/com/fieldbook/tracker/activities/OldDataGridActivity.kt
- app/src/main/java/com/fieldbook/tracker/adapters/DataGridAdapter.java
- app/src/main/java/com/fieldbook/tracker/views/CropImageView.kt
- app/src/main/res/layout/activity_data_grid.xml
- app/src/main/res/layout/activity_data_grid_old.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Use lazytable library for data grid
Closes #743 
Closes #579 
Closes #1211 
```release-note
Data grid updated with new interface
```
___
> New datagrid

- app/src/main/java/com/fieldbook/tracker/preferences/PreferencesFragment.java
- app/src/main/java/com/fieldbook/tracker/utilities/NearbyShareUtil.kt
Fixes crashes while tapping a search result in settings caused by lifecycle issues in NearbyShareUtil
```release-note
Fixed an issue with Settings search
```
___
> Fix settings search crash

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
- app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
- app/src/main/java/com/fieldbook/tracker/database/migrators/ExampleMigratorVersionN.kt
- app/src/main/java/com/fieldbook/tracker/database/migrators/FieldBookMigrator.kt
> init migrator interface for upcoming db version changes

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
Closes #1212
```release-note
Traits with quotes now export correctly in table format
```
___
> added double quote string sanitation to DataHelper

- app/src/main/res/values/styles.xml
closes #1199
```release-note
Device dark mode no longer affects Field Book UI
```
___
> fix dark theme issues app-wide with forced light theme

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
- app/src/main/java/com/fieldbook/tracker/adapters/TraitsStatusAdapter.kt
- app/src/main/java/com/fieldbook/tracker/views/TraitBoxView.kt
- app/src/main/res/layout/view_trait_box.xml
- app/src/main/res/values-sw600dp/dimens.xml
- app/src/main/res/values-sw720dp/dimens.xml
- app/src/main/res/values/dimens.xml
Closes #1200 
```release-note
Trait indicator icons in Collect now resize as expected
```
___
> Fix trait bar resizing

- app/src/main/java/com/fieldbook/tracker/utilities/FileUtil.java
updated file name sanitation to erase all C0 set characters (0x00-0x1F) and replace some other illegal characters with '_'
Closes #1270
```release-note
Image file name sanitation now removes or replaces more characters
```
___
> Update File Sanitation

- app/src/main/java/com/fieldbook/tracker/traits/TextTraitLayout.kt
Fixes #1303 
```release-note
Return character setting is now interpreted correctly
```
___
> Fix carriage return options behavior

- app/src/main/java/com/fieldbook/tracker/database/DataHelper.java
> Database Fix

- app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
updated get export database data to use obs. var ids instead of names to fix problems when special characters are used in variable names
```release-note
```
___
> Export Database CSV bugfix

- app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
Fixes #1343 
```release-note
```
___
> Save brapi obs db id when syncing
