PhenoApps/Field-Book

app/src/main/java/com/fieldbook/tracker/DataHelper.java, app/src/main/java/com/fieldbook/tracker/brapi/BrapiInfoDialog.java, app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java, app/src/main/java/com/fieldbook/tracker/fields/FieldAdapter.java, app/src/main/java/com/fieldbook/tracker/traits/TraitAdapter.java, app/src/main/java/com/fieldbook/tracker/traits/TraitEditorActivity.java, app/src/main/res/layout/dialog_info.xml, app/src/main/res/values/strings.xml
Displays a dialog when a BrAPI field is selected as the active field. 
Displays a dialog when a non-BrAPI traits is selected or imported when a BrAPI field is the selected field. The dialog will display:
- Once per navigation to the Trait Editor page. After initial showing of dialog, it is not shown again until the user navigates away from the page, and then back to the page. 
The occasions when the dialog is shown for the first time are: 
- Dialog will display when a non-BrAPI trait is made active (visible in field book lingo)
- Dialog will display when CSV of traits is imported
- Dialog will display when trait is manually added. 
The dialog informs the user that fields and traits imported from BrAPI can be exported via BrAPI, but fields and traits imported from csv or created manually …
=> Fie 61 fie 62

app/src/main/java/com/fieldbook/tracker/DataHelper.java, app/src/main/java/com/fieldbook/tracker/brapi/BrapiExportActivity.java, app/src/main/java/com/fieldbook/tracker/preferences/PreferencesFragment.java, app/src/main/res/layout/dialog_brapi_export.xml, app/src/main/res/values/strings.xml
Made it so the auth button appears after the brapi url is changed. Before, the user had to exit and re-enter the settings menu for it to appear. 
Remove the 'Empty Observation Values' category and related code because it was unused.
=> Fix auth btn. Remove unused category from export page.

app/src/main/java/com/fieldbook/tracker/brapi/BrAPIService.java
Added conversions for data types that were left out of the original conversion. Converted the data types to the closest matches in Fieldbook:
"Code" - This scale class is exceptionally used to express complex traits. Code is a nominal scale that combines the expressions of the different traits composing the complex trait. For exemple a severity trait might be expressed by a 2 digit and 2 character code. The first 2 digits are the percentage of the plant covered by a fungus and the 2 characters refer to the delay in development, e.g. "75VD" means "75%" of the plant is Crop Ontology & Integrated Breeding Platform Curation Guidelines 5/6/2016 9 infected and the plant is very delayed.
"Date" - The date class is for events expressed in a time format, e.g. yyyymmddThh:mm:ssZ or dd/mm/yy …
=> Add data conversions for extra BrAPI data types

app/src/main/java/com/fieldbook/tracker/brapi/BrAPIService.java, app/src/main/java/com/fieldbook/tracker/brapi/BrapiActivity.java, app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java, app/src/main/java/com/fieldbook/tracker/brapi/BrapiTraitActivity.java, app/src/test/java/BrapiServiceTest.java
Applied changes to send the authorization token to the following GET requests:
- GET /studies
- GET /studies/{studyDbId}
- GET /studies/{studyDbId}/observationunits
- GET /studies/{studyDbId}/observationvariables
- GET /variables
Fixes # https://github.com/PhenoApps/Field-Book/issues/96
1. Set the BrAPI URL, save and authorize
2. In the Fields section, import from BrAPI
3. A list of fields (studies) should be displayed
4. Select a field then click Save Field
5. A dialog box will appear showing the Name, Description, Location, Number of Plots and Traits
6. Verify that the …
=> Send authorization token in GET requests.

app/src/main/java/com/fieldbook/tracker/activities/BrapiActivity.java, app/src/main/java/com/fieldbook/tracker/activities/BrapiExportActivity.java, app/src/main/java/com/fieldbook/tracker/activities/BrapiTraitActivity.java, app/src/main/java/com/fieldbook/tracker/brapi/ApiError.java, app/src/main/java/com/fieldbook/tracker/brapi/BrAPIService.java, app/src/main/res/values-es/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/BrapiServiceTest.java
- Display a special error message for http status 400, 403 and 404
- If http status 401, start BrapiAuthDialog
- Consolidate error codes in ApiError enum
Basically this branch implements a similar workflow already available in the BrAPI export activity.
Fixes #130
Tested with:
- Android Studio emulator - Pixel 2 API 28 
- and generated Apk on Moto G6 Plus
Tests:
- In the BrAPI authorization settings, log in to BMS with a user with no permission for studies, and authorize Field book.
- Go to Fields and load studies. See special error message: _ERROR: You do not have the permissions necessary for the specified system._
cc @trife @BrapiCoordinatorSelby @mcrimi @clarysabel
=> Handle http error status in BrAPI Field and Traits activities

app/src/main/java/com/fieldbook/tracker/brapi/BrapiObservation.java, app/src/main/java/com/fieldbook/tracker/database/DataHelper.java, app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
Changed brapi observation time formatter back to SSSZZZZZ
Bug fix for AOB exception occurring if the range table wasn't created when getAllRangeID is called.
Bugfix (I think just for emulators) if the SSSZZZZZ format can't parse due to not having a time zone, an empty string is given.
=> Bugfixes from refactor merge

app/src/main/java/com/fieldbook/tracker/database/Migrator.kt
fixes #224 
Null traits where causing a crash during migration from v8 -> v9. I added a check to convert the null values to empty strings before they are migrated.
- [ x] Bug fix (non-breaking change which fixes an issue)
On emulator:
installed v8, inserted a null value category, installed develop branch and migrated to v9 (no crash)
=> Added default empty string when null traits are migrated

app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt
#260 but for images
Fixes #257 
Verified that images are no longer duplicated in BrAPI export window:
=> fix duplicated images in brapi export (#260 but for images)

app/src/main/java/com/fieldbook/tracker/activities/BrapiTraitActivity.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIService.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java, app/src/main/res/values/strings.xml
The issue was that the brapi server had variables with only a variable name and a `null` in the `trait` field. It looks as if the trait information is required for the field book trait, so I skipped any variable that did not have the `trait` field. 
Fixes # https://github.com/PhenoApps/Field-Book/issues/250
I tested it by following @chaneylc bug reproduction steps:
1. Enable V2 and authorize on the test server.
2. Go to Traits from config activity.
3. Go to import -> brapi
4. Crash
You can confirm that the brapi test server has variables that would cause an error with the fix by using an api client to inspect the result of `GET https://test-server.brapi.org/brapi/v2/variables`.
=> issue 250 trait import brapi v2 error

app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java
In the BrAPI v1 service there was a line that was adding the plots to the study details twice. I removed that line to fix the duplicate plot issue. I wasn't able to reproduce the issue from the bug, but I was able to see the duplicates in the `observation_units` table in the database. 
I checked out BrAPI Service v2 and it looks like it doesn't have this bug. 
Fixes # https://github.com/PhenoApps/Field-Book/issues/257
I was not able to reproduce the bug on the issue, https://github.com/PhenoApps/Field-Book/issues/257, but I was able to see the duplicates in the database. You need to use brapi v1 for this test, so there are some hack-arounds with the token to interact with the brapi test server. 
- Go into the code and change …
=> issue 257 duplicate plots

app/build.gradle, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
Updates the brapi client library to the newest version which allows for any object in the additional info fields. 
Instead of refactoring the image additional info fields, I just removed them since they weren't being used. My thoughts were that we can add that field back in the future if there is a need for it. I can also refactor it now if you would rather do that. 
Fixes # https://github.com/PhenoApps/Field-Book/issues/295
I tested this against the brapi test server:
1. Set brapi test server as the Field Book server
2. Checked that GET /variables returns additional info with …
=> Fix brapi additional info bug

app/src/main/java/com/fieldbook/tracker/activities/FieldEditorActivity.java, app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
This branch has a couple of bugfixes.
1. The  getDropDownRange(uniqueName: String, trait: String, plotId: String): Array<String>
The second parameter can actually be an observation unit property name, which needs to be sanitized. In some cases Unique is used which is an Sqlite keyword or it contains spaces.
2. In FieldEditorActivity empty strings could be selected when importing a field file.
The solution was to not add empty strings to the selection.
=> Added sanitized column names, added empty column check on import

app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java, app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitPropertyDao.kt
Previously the convertDatabaseToTable function used left joins to pivot our EAV data where observation variable names would appear as headers. SQLite has a limitation on the number of left joins that can occur in a query (65). This implementation uses aggregation case statements to pivot the table, removing the need for multiple left joins.
Example: (more detail described in documentation of convertDatabaseToTable)
``` 
SELECT props.*,
MAX(CASE WHEN (o.observation_variable_name='height') THEN o.value ELSE NULL END) AS 'height',
MAX (CASE WHEN o.observation_variable_name='flowering' THEN o.value ELSE NULL END) AS 'flowering',
MAX (CASE WHEN o.observation_variable_name='insect damage' THEN o.value ELSE NULL END) AS 'insect damage'
FROM ObservationUnitProperty as props
LEFT JOIN observations …
```
=> Allowing >64 traits in table export

app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java, app/src/test/java/BrapiServiceTest.java
Modified `BrAPIServiceV1#getPlotDetails` and `BrAPIServiceV2#getPlotDetails` to use the `BRAPI_PAGE_SIZE` setting.  In `BrAPIServiceV1#getPlotDetails` fixed a bug where plots fetched on each page request override plots fetched on previous page request.
Fixes #335 
- [ x ] Bug fix (non-breaking change which fixes an issue)
Prereq: setup BrAPI connection info:
1. URL to a BrAPI server with a study with more than 1000 observationUnits
2. BrAPI V1
Test A:
1. Go to Fields
2. Click on the + to add a new field
3. Choose "BrAPI"
4. Choose appropriate study
5. Click "Save Field"
6. Click "Ok"
7. Go to Collect
8. Cycle through observationunits to see that all observationunits are present
Test B:
1. Modify the `pageSize` BrAPI setting to 500
2. Go to …
=> Modifying fetching of plots to use BRAPI_PAGE_SIZE setting

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java, app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIService.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java, app/src/main/java/com/fieldbook/tracker/database/dao/ObservationUnitAttributeDao.kt, app/src/main/res/values/strings.xml
Added checks in BrAPI code that disallows importing studies with 0 plots.
Added check in Collect activity that will finish activity if 0 plots are found (instead of crashing).
Fixes #299
=> Fixed crash when navigating to Collect with a study that has 0 plots

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java, app/src/main/res/raw/changelog.xml
QuickGoto search now uses both primary/secondary terms if they are changed. Otherwise it does the default search with the last changed term.
Fixes #157
=> Improved quick goto search.

app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java, app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java, app/src/main/java/com/fieldbook/tracker/preferences/ProfilePreferencesFragment.java, app/src/main/res/drawable/ic_card_account_details_outline.xml, app/src/main/res/drawable/ic_refresh.xml, app/src/main/res/raw/changelog.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_profile.xml
issue #274 
Added user id to crashlytics. This id can be refreshed/enabled in the profile preferences. The id is saved in the shared preferences, and the crashlytics api is updated when config activity starts, or the id is updated. The preference is disabled by default. The user id is also added as a data key under "user_token".
=> V5.3/features/274

app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
Added more trait format options when importing obs. vars. from brapi now the user can have obs. vars. with field book trait formats, instead of having to edit them after import.
Updated convert brapi data type function in v1 and v2 to allow for fieldbook trait formats to be used.
Fixes #512
=> Bug 512 added ability to import obs. vars. that already have FB formats defined

app/src/main/java/com/fieldbook/tracker/activities/BrapiActivity.java, app/src/main/java/com/fieldbook/tracker/adapters/FieldAdapter.java, app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java, app/src/main/java/com/fieldbook/tracker/brapi/model/BrapiStudyDetails.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIService.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrapiPaginationManager.java, app/src/main/java/com/fieldbook/tracker/database/DataHelper.java, app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt, app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt, app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt, app/src/main/res/layout/dialog_brapi_sync_observations.xml, app/src/main/res/menu/menu_field_listitem.xml, app/src/main/res/values/strings.xml
This Pull Request will allow the user to pull down existing Observations for a BrAPI study.  This is not done automatically, but rather through a Dialog that is completely optional.  This allows for users to update fields on devices depending on what was scored on different devices
I have tested this for test fields stored in Breedbase pulling down ~150 observations for both BrAPI v1 and v2.  I have also tested the pagination by setting pageSize to 10 and pulling down the same study.
* Motorola G series phones from 2020-2022
* SDK: Recent versions of Android, unknown exactly.
=> BrAPI Observation Syncing

app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
Fixes #648.  Observation sync code no longer hangs.
```release-note
Now correctly displays the Save Button once the requested pages have all been downloaded.
```
=> Fixing issue with Observation Syncing Save Button not showing up.

app/src/main/java/com/fieldbook/tracker/objects/FieldFileObject.java
XLSX formulas weren't being evaluated when imported.
```release-note
Support for formulas in XLSX files.
```
=> xlsx formula fix for field import files

app/src/main/res/layout/list_item_search_constructor.xml
The search feature in Collection had spinners centered in the screen, pushing the text entry field out of view, so it was not possible to search:
I modified the box layout by giving the spinners and the text field equal weights. This seems pulls the text field back into visibility. 
**I am not an experienced Android developer, so I don't know if this is the best way to accomplish this. Maybe there is another, preferred way!**
```Fixed missing text entry field in search.
```
=> fixed search box so text entry field is visible

app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt, app/src/main/res/layout/dialog_brapi_sync_observations.xml, app/src/main/res/values/strings.xml
This addresses user not knowing when the brapi call is done as discussed in  issue #648.  The Syncing code will now throw up a warning message if something either happens during collecting the pages or if there are no observations found when downloading the observations.  This was internally tested with both a new field and a field which has observations within it and it works in both cases.
```release-note
Added in a warning message and removed the loading spinner when Fieldbook is done pulling Observations when there are no observations currently associated with the field.
```
=> Adding in no observation warning message For Observation Syncing

app/src/main/java/com/fieldbook/tracker/dialogs/NewTraitDialog.java
Refactors new trait category addition, so addition method can be run a final time on trait save even if add button is not clicked.
Closes #572
```release-note
autosave final trait category during new trait creation
```
=> autosave final trait category during new trait creation

app/src/main/java/com/fieldbook/tracker/brapi/BrapiLoadDialog.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java, app/src/main/java/com/fieldbook/tracker/objects/TraitObject.java
This is a short-term solution for [684](https://github.com/PhenoApps/Field-Book/discussions/684).
This code change will handle observationLevelNames metadata in additionalInfo (e.g., {"observationLevelNames": ["plot", "plant"]}) for BrAPI GET 2.x variables (BMS specific). This metadata helps identify the level(s) at which a variable is utilized within a study/field. The information will be utilized to filter the variables based on the selected Observation Level during BrAPI Field Import, ensuring that only relevant variables will be added.
```release-note
Fix BRAPI 2.0 integration with BMS. …
```
=> Bms integration fix

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java, app/src/main/java/com/fieldbook/tracker/interfaces/CollectRangeController.kt, app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java, app/src/main/java/com/fieldbook/tracker/views/RangeBoxView.kt, app/src/main/java/com/fieldbook/tracker/views/TraitBoxView.kt, app/src/main/res/drawable/ic_adv_return_first_trait.xml, app/src/main/res/raw/changelog.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_behavior.xml
Adds preference that returns traitbox to first trait when entry is advanced
closes #722
```release-note
Added a behavior option to return to first trait when entry is advanced.
```
=> adds preference to return to first trait

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java, app/src/main/java/com/fieldbook/tracker/preferences/BehaviorPreferencesFragment.java, app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java, app/src/main/java/com/fieldbook/tracker/preferences/GeneralPreferencesFragment.java, app/src/main/res/raw/changelog.xml, app/src/main/res/values/array.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_behavior.xml
Converts volume button navigation setting from checkbox to list with 'Disabled', 'Trait Navigation', and 'Entry Navigation' as options.
closes #712
```release-note
Added trait navigation to volume button options
```
=> Add trait navigation to Volume button options

app/src/main/java/com/fieldbook/tracker/utilities/CategoryJsonUtil.kt
Bugfix for old string values for categorical traits not being parsed correctly.
```release-note
Bugfix loading old categorical observation values
```
=> bugfix loading old categorical observation values

app/src/main/java/com/fieldbook/tracker/traits/TextTraitLayout.kt
feat: don't select all text for text traits, before it was selecting/highlighting the existing data
```release-note
Text trait data is not automatically selected anymore.
```
=> Don't select all data for Text traits

.github/workflows/github-release.yml
Fix `Error: Couldnt find the Android build tools @ /usr/local/lib/android/sdk/build-tools/29.0.3` by explicitly installing the necessary build-tools version.
```release-note
```
=> Fix build-tools error in github-release.yml

app/src/main/java/com/fieldbook/tracker/traits/TextTraitLayout.kt
Fixed issue, tested on Boox and Pixel 6. Also tested USB barcode scanner to make sure it was still functional.
```release-note
Bugfix for entering digits in a text trait on some keyboards
```
=> bugfix for text traits not entering digits correctly

app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java, app/src/main/java/com/fieldbook/tracker/database/DataHelper.java, app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt, app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt, app/src/test/java/BrapiServiceTest.java
Fixing Observation Syncing to properly link the observations with the traits and plots based on internal ids instead of by names.
```release-note
Fixed a bug causing the Observation Syncing to do nothing.
```
=> Fixing Observation Syncing to use internal DB ids instead of trait names

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java, app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java
Adds handler to skip the filepicker and directly open the last used resource file when the resource file icon is longpressed
closes #921
```release-note
longpress on resource file icon directly opens last used file
```
=> save last used res file to open on longpress

app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV2.java
Addresses problems with germplasm retrieval breaking study imports. Makes germplasm detail object nullable to handle cases where `/search/germplasm` isn't implemented (BIMS) and adds a client-controlled paging check to prevent endless requests when server paging has errors (Deltabreed). 
closes #962
closes #954
```release-note
Improved germplasm retrieval during study imports
```
=> Germplasm call refinements

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java, app/src/main/java/com/fieldbook/tracker/preferences/LanguagePreferenceFragment.kt, app/src/main/java/com/fieldbook/tracker/traits/CategoricalTraitLayout.java, app/src/main/java/com/fieldbook/tracker/traits/LayoutCollections.java, app/src/main/java/com/fieldbook/tracker/traits/MultiCatTraitLayout.java, app/src/main/java/com/fieldbook/tracker/utilities/Utils.java, app/src/main/res/layout/activity_collect.xml, app/src/main/res/values/strings.xml
Adds toasts when locked status is changed and toast plus error sound when locked interface is clicked.
Adds dialog when language is switched to warn that translations are crowd-sourced and may be incomplete  
Closes #915 and #890
```release-note
Explanatory info added to lock and languages changes
```
=> Ux enhancements - explanatory info on lock and language changes

app/src/main/java/com/fieldbook/tracker/preferences/LanguagePreferenceFragment.kt
Previously this was not working, now it correctly sets the app language to the default system language.
```release-note
```
=> Fix Set System Default Language in appearances

app/src/main/java/com/fieldbook/tracker/utilities/ExportUtil.kt, app/src/main/res/values/strings.xml
fix #576
warning when exporting table with repeated measures enabled, table format only shows the latest repeated measure
```release-note
```
=> v5 repeated measures export warning

app/src/main/java/com/fieldbook/tracker/utilities/DocumentTreeUtil.kt
fix #908
added .nomedia file to trait and field data dirs
```release-note
```
=> added .nomedia to trait and field data dirs

app/src/main/java/com/fieldbook/tracker/preferences/ExperimentalPreferencesFragment.kt
fix #853
auto enable geonav and limited log when field audio is enabled in settings
```release-note
```
=> Field audio sets geonav and limited log 

app/src/main/java/com/fieldbook/tracker/traits/GNSSTraitLayout.kt
fix #587
updated GNNS trait to warn user of updating saved coordinate only after revisiting that entry
```release-note
```
=> v5 geo coordinate warning update

app/src/main/java/com/fieldbook/tracker/traits/GNSSTraitLayout.kt, app/src/main/java/com/fieldbook/tracker/views/RepeatedValuesView.kt, app/src/main/res/layout/view_repeated_values.xml, app/src/main/res/values/strings.xml
fixes #854 
After field testing this, user chosen precision acts as a minimum not by match in geonav and gnss.
I found two ui related bugs that this PR fixes including:
1. switching from float rtk to rtk in gnss, user could quickly press collect to save an observations and bypass the precision requirement (when precision is GPS)
2. minor repeated measures visual bug
```release-note
```
=> v5 geonav ui bugfixes

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/github-release.yml, .github/workflows/update-changelog.yml, CHANGELOG.md
…emplate
Adds three release type checkboxes to the PR template and updates actions to make use of them.
Also simplifies change type checkboxes to match release note structure.
Releases can now triggered three ways:
-   When a PR is merged , a MAJOR or MINOR release can be dispatched by checking the corresponding release type checkbox, or deferred by checking WAIT
-   Releases can also be triggered manually by using workflow dispatch (release type is taken as an argument).
-   The release action is also scheduled to check once a week (Monday 3pm EST) if there have been changes to the app directory since the last release, if it finds any it makes a new PATCH release.
```release-note
```
=> Add release type checkboxes to PR template

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java, app/src/main/res/values/strings.xml
```release-note
Long-pressing delete button on bottom toolbar will remove all observations for that trait
```
___
=> long_press_delete

app/src/main/java/com/fieldbook/tracker/activities/brapi/io/filter/BrapiListFilterActivity.kt, app/src/main/java/com/fieldbook/tracker/activities/brapi/io/filter/BrapiSubFilterListActivity.kt, app/src/main/java/com/fieldbook/tracker/activities/brapi/io/filter/filterer/BrapiStudyFilterActivity.kt, app/src/main/java/com/fieldbook/tracker/activities/brapi/io/filter/filterer/BrapiTraitFilterActivity.kt
```release-note
Fields and traits that have already been imported are now hidden on the BrAPI import screen
```
___
=> brapi_hide_previously_imported

app/src/main/java/com/fieldbook/tracker/activities/brapi/io/BrapiStudyImportActivity.kt
```release-note
Accession number now included for germplasm imported via BrAPI
```
___
=> brapi_germ_accession_number

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
```release-note
Go to ID dialog now has cursor focus when opened
```
___
=> collect_go_to_id_dialog_focus

app/src/main/java/com/fieldbook/tracker/preferences/StoragePreferencesFragment.java
```release-note
Improved database export messaging
```
___
=> fix_error_msg_when_db_pref_export_fails

app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java, app/src/main/java/com/fieldbook/tracker/traits/LabelPrintTraitLayout.java, app/src/main/java/com/fieldbook/tracker/utilities/BluetoothUtil.kt, app/src/main/java/com/fieldbook/tracker/utilities/PrintThread.kt
Updates LabelPrintTraitLayout, BluetoothUtil.print() and PrintThread to include the current plot and trait in the broadcast intent as additional info, then uses them on receipt of a successful print message to store the  print observation to the correct plot and trait, even if the user has since moved on.
Closes #1106
```release-note
Label print observations are now assigned to the correct entry when navigating before the print is complete
```
___
=> Eliminate possibility of incorrect plot/trait assignment during label printing

app/src/main/java/com/fieldbook/tracker/preferences/GeneralKeys.java, app/src/main/java/com/fieldbook/tracker/preferences/SystemPreferencesFragment.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_system.xml
```release-note
Setting added to reset preferences to default
```
___
=> setting_to_reset_all_settings

app/src/main/java/com/fieldbook/tracker/traits/PercentTraitLayout.java
Modifies code that displays collected percent values to use default of 100 if max is not set. This prevents crashes if max is not set and data has been collected, and [is consistent with the default max value used on init of the empty format](https://github.com/PhenoApps/Field-Book/blob/6dbbd7d903cbacecc676b0040efaa4f5acdb6465/app/src/main/java/com/fieldbook/tracker/traits/PercentTraitLayout.java#L56).
closes #1126
```release-note
Percent traits imported via BrAPI without min and max values default to 0/100
```
___
=> display with default max of 100 if max not set

.github/workflows/github-release.yml, app/src/main/res/raw/changelog.xml
Adds step to update changelog.xml file in github release action
closes #605
```release-note
```
___
=> Include changelog.xml update in release action

app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiActivity.java, app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiExportActivity.java, app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiProgramActivity.java, app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiTraitActivity.java, app/src/main/java/com/fieldbook/tracker/activities/brapi/BrapiTrialActivity.java, app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIService.java
closes #520
```release-note
BrAPI export no longer crashes when authentication token is expired
```
___
=> brapi_export_window_leak_fix

app/src/main/AndroidManifest.xml
Some Android devices cannot connect to a BrAPI server and immediately get "Error Starting BrAPI Auth", while on other devices the authorization proceeds to the login page.
After quite some debugging, the issue was narrowed down to a missing intent in the manifest file. Some Androids require `VIEW` `BROWSABLE` intent in the manifest. Without it, the list of browsers available for BrAPI auth is blank, the BrAPI login page cannot be shown, and the app fails with "Error Starting BrAPI Auth".
```release-note
BrAPI authorization fix for specific devices
```
___
=> BrAPI: Fix issue with starting BrAPI authorization

app/src/main/java/com/fieldbook/tracker/traits/GNSSTraitLayout.kt
```release-note
GNSS trait no longer resets connection when moving between entries
```
___
=> fix gnss trait receiver not registering after moving between entries

app/src/main/java/com/fieldbook/tracker/utilities/ExportUtil.kt
Fixes #995 
```release-note
Bundled media is now exported as expected for active and existing traits
```
___
=> Export only active trait media files

app/src/main/java/com/fieldbook/tracker/activities/brapi/io/mapper/PhenotypingMapper.kt
replaces deprecated min and max methods in PhenotypingMapper used by new brapi trait import. closes #1228
```release-note
BrAPI min/max values are now imported correctly
```
___
=> min max fix for new import

app/src/main/java/com/fieldbook/tracker/traits/DateTraitLayout.java, app/src/main/java/com/fieldbook/tracker/views/CollectInputView.kt, app/src/main/java/com/fieldbook/tracker/views/RepeatedValuesView.kt
TODO: possibly add date trait intermediate representation
fixes #1268
```release-note
Repeated measures no longer ignore trait limits
```
___
=> added data validation to repeated measures

app/src/main/java/com/fieldbook/tracker/activities/brapi/io/BrapiStudyImportActivity.kt, app/src/main/java/com/fieldbook/tracker/activities/brapi/io/BrapiTraitImporterActivity.kt, app/src/main/java/com/fieldbook/tracker/adapters/TraitAdapter.kt, app/src/main/java/com/fieldbook/tracker/dialogs/BrapiSyncObsDialog.kt
fixes #1252
```release-note
New traits from BrAPI now appear at the end of the trait list
```
___
=> adds new brapi traits to end of the trait list

app/src/main/java/com/fieldbook/tracker/database/dao/StudyDao.kt
Fixes the bug where field detail page showed same completed % for all traits
```release-note
```
___
=> Fix trait completeness to calculate per-trait distinct_obs_units
